/**
 * Lista de cidades portuguesas para o filtro CITY na homepage
 */
export const CITIES_PT = [
  "Abrantes",
  "Agualva-Cacém",
  "Águeda",
  "Albufeira",
  "Alcácer do Sal",
  "Alcobaça",
  "Almada",
  "Almeirim",
  "Alverca do Ribatejo",
  "Amadora",
  "Amarante",
  "Angra do Heroísmo",
  "Aveiro",
  "Barcelos",
  "Beja",
  "Braga",
  "Bragança",
  "Caldas da Rainha",
  "Caniço",
  "Cartaxo",
  "Castelo Branco",
  "Chaves",
  "Coimbra",
  "Coruche",
  "Covilhã",
  "Elvas",
  "Entroncamento",
  "Espinho",
  "Esposende",
  "Estarreja",
  "Estremoz",
  "Évora",
  "Fafe",
  "Faro",
  "Felgueiras",
  "Figueira da Foz",
  "Freamunde",
  "Funchal",
  "Gafanha da Nazaré",
  "Gondomar",
  "Gouveia",
  "Guarda",
  "Guimarães",
  "Horta",
  "Ílhavo",
  "Lagoa",
  "Lagos",
  "Lamego",
  "Leiria",
  "Lisboa",
  "Lixa",
  "Loulé",
  "Loures",
  "Lourosa",
  "Macedo de Cavaleiros",
  "Machico",
  "Maia",
  "Mangualde",
  "Marco de Canaveses",
  "Marinha Grande",
  "Matosinhos",
  "Mealhada",
  "Mêda",
  "Miranda do Douro",
  "Mirandela",
  "Montemor-o-Novo",
  "Montijo",
  "Moura",
  "Odivelas",
  "Olhão",
  "Oliveira de Azeméis",
  "Oliveira do Bairro",
  "Ourém",
  "Ovar",
  "Paços de Ferreira",
  "Paredes",
  "Penafiel",
  "Peniche",
  "Peso da Régua",
  "Pinhel",
  "Pombal",
  "Ponta Delgada",
  "Ponte de Sor",
  "Portalegre",
  "Portimão",
  "Porto",
  "Póvoa de Santa Iria",
  "Póvoa de Varzim",
  "Praia da Vitória",
  "Queluz",
  "Rebordosa",
  "Reguengos de Monsaraz",
  "Ribeira Grande",
  "Rio Maior",
  "Rio Tinto",
  "Sabugal",
  "Sacavém",
  "Santa Comba Dão",
  "Santa Maria da Feira",
  "Santana",
  "Santarém",
  "Santiago do Cacém",
  "Santo Tirso",
  "Seia",
  "Seixal",
  "Serpa",
  "Setúbal",
  "Silves",
  "Sines",
  "Tarouca",
  "Tavira",
  "Tomar",
  "Tondela",
  "Torres Novas",
  "Torres Vedras",
  "Trancoso",
  "Trofa",
  "Valbom",
  "Valença",
  "Valongo",
  "Vendas Novas",
  "Viana do Castelo",
  "Vila Baleira",
  "Vila do Conde",
  "Vila Franca de Xira",
  "Vila Nova de Famalicão",
  "Vila Nova de Gaia",
  "Vila Nova de Santo André",
  "Vila Real",
  "Vila Real de Santo António",
  "Viseu",
  "Vizela",
];
